steps:
# Build Docker Image 
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/ca-k8s-340019/frontend:staging', '.']

#Push Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ca-k8s-340019/frontend:staging']

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
    --filename=create-nodejs-service-manifest.yaml
    --location=europe-west2
    --cluster=k8s-ca-cluster
  
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
    --filename=routing.yaml
    --location=europe-west2
    --cluster=k8s-ca-cluster
    
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
    --filename=canary.yaml
    --location=europe-west2
    --cluster=k8s-ca-cluster


