steps:
# Build Docker Image 
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/ca-k8s-340019/frontend:latest', '.']

#Push Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ca-k8s-340019/frontend:latest']
