apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 22137
  selector:
    app: node

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: node    
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: gcr.io/ca-k8s-340019/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 22137
          name: http
          protocol: TCP      

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-deployment
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: node-deployment
    kind: Deployment
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
