apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v2
  labels:
    app: node
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
      version: v2
  template:
    metadata:
      labels:
        app: node
        version: v2
    spec:
      serviceAccountName: frontend-details
      containers:
        - name: reviews
          image: gcr.io/ca-k8s-340019/frontend:stagging
          imagePullPolicy: Always
          ports:
            - containerPort: 22137
              name: http
              protocol: TCP
