name: Docker
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: frontend
      PROJECT_ID: ca-k8s-340019
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .


    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
    
    - name: Push Docker Image to Container Registry (GCR)
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
